import type { Metadata } from "next";
import { Inter, Inter as FontSans } from "next/font/google";
import "./globals.css";
import React from "react";
import { cn } from "@/lib/utils";
import { NextFont } from "next/dist/compiled/@next/font";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans"
});

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={cn(fontSans.className)}>
                {children}
            </body>
        </html>
    );
}
